//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class classroom_allocation_data
    {
        public int ca_id { get; set; }
        public Nullable<System.DateTime> day { get; set; }
        public Nullable<System.TimeSpan> start_time { get; set; }
        public Nullable<System.TimeSpan> end_time { get; set; }
        public Nullable<int> t_id { get; set; }
        public Nullable<int> class_id { get; set; }
        public Nullable<int> sub_id { get; set; }
    
        public virtual classroom classroom { get; set; }
        public virtual teacher teacher { get; set; }
        public virtual subject subject { get; set; }
    }
}
