//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class computer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public computer()
        {
            this.repairs = new HashSet<repair>();
        }
    
        public int LabNo { get; set; }
        public int MachineNO { get; set; }
        public string Processor_Type { get; set; }
        public string Motherboard_ID { get; set; }
        public string PowerSupply_ID { get; set; }
        public string RAM_Capacity { get; set; }
        public string HDD_Capacity { get; set; }
    
        public virtual lab lab { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<repair> repairs { get; set; }
    }
}
