//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tute
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tute()
        {
            this.student_tute = new HashSet<student_tute>();
        }
    
        public int tute_id { get; set; }
        public string title { get; set; }
        public Nullable<System.DateTime> upload_date { get; set; }
        public Nullable<int> t_id { get; set; }
        public Nullable<int> sub_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<student_tute> student_tute { get; set; }
        public virtual subject subject { get; set; }
        public virtual teacher teacher { get; set; }
    }
}
